### ISSUE TITLE
running build() without parameters causes  (node:22117) UnhandledPromiseRejectionWarning: Error: `gasPrice` is not defined.

### ISSUE THREAD

**Issue by paulvi** [InstaDApp/dsa-sdk#108]
https://docs.instadapp.io/setup/ shows example as 

    dsa.build().then(console.log);
    
and says that `build` has 
    >an optional Object parameter

However running build() without parameters causes 

(node:22117) UnhandledPromiseRejectionWarning: Error: `gasPrice` is not defined.
    at f.exports.getTxObj (/Users/user/Workspaces/Ethereum/Instadapp/instadapp-get-started/node_modules/dsa-sdk/build/dsa.min.js:12:395221)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/user/Workspaces/Ethereum/Instadapp/instadapp-get-started/node_modules/dsa-sdk/build/dsa.min.js:12:41342
(

So either docs or current version of sdk are wrong.

**Comment by Sowmayjain** [comment]
@paulvi could you use this SDK instead?

https://github.com/instadapp/dsa-connect

**Comment by paulvi** [comment]
Do you mean that "Documentation" link from https://instadapp.io/ was wrong
and the content of https://docs.instadapp.io/ is of no use?

So https://github.com/instadapp/dsa-connect is newer SDK version
